version: '3'
networks:
  custom-network:
    ipam:
      config:
        - subnet: 192.168.0.0/24 # 
services:
  navconnect:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 192.168.0.202:8000
    ports:
      - "8000:8000"
    networks:
      custom-network:
        ipv4_address: 192.168.0.202
